site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'blog'
    label: 'Blog Yazıları'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - {
          label: 'Oluşturma Tarihi',
          name: 'createdAt',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'YYYY-MM-DD',
          time_format: false,
        }
      - { label: 'Başlık', name: 'title', widget: 'string', required: true }
      - { label: 'Açıklama', name: 'description', widget: 'string', required: false }
      - { label: 'Ana Görsel', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'İçerik', name: 'body', widget: 'markdown', required: false }
  - name: 'projects'
    label: 'Projeler'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Proje Kategorisi',
          name: 'category',
          widget: 'select',
          default: 'proj1',
          options:
            [
              { label: 'YG/AG Enerji Nakil Hatları Projeleri', value: 'proj1' },
              { label: 'Endüstriyel Tesis Projeleri', value: 'proj2' },
              { label: 'OG Trafo Projeleri', value: 'proj3' },
              { label: 'Konut ve Çok Katlı Bina Projeleri', value: 'proj4' },
              { label: 'AG Tesis ve İç Tesisat Projeleri', value: 'proj5' },
              { label: 'Uygulama Projeleri', value: 'proj6' },
              { label: 'Busbar Dağıtım Tesisleri', value: 'proj7' },
              { label: 'Jeneratör Projeleri', value: 'proj8' },
              { label: 'SCADA Projelendirmeleri', value: 'proj9' },
              { label: 'GES Projelendirmeleri', value: 'proj10' },
              { label: 'Deplase İşleri', value: 'proj11' },
              { label: 'Abonelik ve Talep Açma İşlemleri', value: 'proj12' },
            ],
        }
      - { label: 'Başlık', name: 'title', widget: 'string', required: true }
      - { label: 'Açıklama', name: 'description', widget: 'string', required: false }
      - { label: 'Ana Görsel', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'İçerik', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Görsel Galerisi',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
